# This file was generated by GoReleaser. DO NOT EDIT.
class Dockma < Formula
  desc "Level up your docker-compose game!"
  homepage "https://github.com/martinnirtl/dockma"
  version "1.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/martinnirtl/dockma/releases/download/v1.0.3/dockma-1.0.3-darwin-x86_64.tar.gz"
    sha256 "216c32aa48cba31b09e0a78ceffc85d0106a72a4b7127337c460b0e63e63fbd4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/martinnirtl/dockma/releases/download/v1.0.3/dockma-1.0.3-linux-x86_64.tar.gz"
      sha256 "16b779ccafc71a045981586b61002c055aaf8a96815bb7fa2447f85a7af5f20c"
    end
  end

  def install
    bin.install "dockma"
  end

  test do
    system "#{bin}/dockma version"
  end
end
