# This file was generated by GoReleaser. DO NOT EDIT.
class Dockma < Formula
  desc "Level up your docker-compose game!"
  homepage "https://github.com/martinnirtl/dockma"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/martinnirtl/dockma/releases/download/v1.0.0/dockma-1.0.0-darwin-x86_64.tar.gz"
    sha256 "06b769cc822fcf601daf0507bdc4bcb39d300cc42d57c35e54758e951758f24b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/martinnirtl/dockma/releases/download/v1.0.0/dockma-1.0.0-linux-x86_64.tar.gz"
      sha256 "1be3db2a1556d0bd5ec32df9c625fd7960fea9afc158c99673dfedd68425a7b4"
    end
  end

  def install
    bin.install "dockma"
  end

  test do
    system "#{bin}/dockma version"
  end
end
