# This file was generated by GoReleaser. DO NOT EDIT.
class Dockma < Formula
  desc "Level up your docker-compose game!"
  homepage "https://github.com/martinnirtl/dockma"
  version "1.0.0-alpha4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/martinnirtl/dockma/releases/download/v1.0.0-alpha4/dockma-1.0.0-alpha4-darwin-x86_64.tar.gz"
    sha256 "dae53a2d79fb252490561ed1274f1a76fdfbd721c7a0ffbace9d3af753555543"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/martinnirtl/dockma/releases/download/v1.0.0-alpha4/dockma-1.0.0-alpha4-linux-x86_64.tar.gz"
      sha256 "c6e741303849eafb9035ed107c66196ab499e0ccd88946ca7ae5c3e227314668"
    end
  end

  def install
    bin.install "dockma"
  end

  test do
    system "#{bin}/dockma version"
  end
end
