# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hosts < Formula
  desc "Manage host entries - a simple tool for a simple, but annoying task!"
  homepage "https://github.com/martinnirtl/hosts-cli"
  version "0.4.2"

  on_macos do
    url "https://github.com/martinnirtl/hosts-cli/releases/download/v0.4.2/hosts_macos_all.tar.gz"
    sha256 "15c7e38f29e6eaa5ed31730f6240bd99bcbd2a9935af6c6a7cf45df9b4261376"

    def install
      bin.install "hosts"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/martinnirtl/hosts-cli/releases/download/v0.4.2/hosts_linux_x86_64.tar.gz"
      sha256 "089476cfbc30756bfa95c117008a0a15e2c777229b21d06e597f9434f4da2b11"

      def install
        bin.install "hosts"
      end
    end
  end
end
