# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hosts < Formula
  desc "Manage host entries - a simple tool for a simple, but annoying task!"
  homepage "https://github.com/martinnirtl/hosts-cli"
  version "0.3.1"

  on_macos do
    url "https://github.com/martinnirtl/hosts-cli/releases/download/v0.3.1/hosts_macos_all.tar.gz"
    sha256 "5c0af7b20120509dd4eb568b862b1e9eb0641bcdc38c9c0bbf35a630848d2ac5"

    def install
      bin.install "hosts"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/martinnirtl/hosts-cli/releases/download/v0.3.1/hosts_linux_x86_64.tar.gz"
      sha256 "31435ad48d0b0680a3c18675e2fb3ccfd399fd9deabd4e4e594a6f5b6816ac68"

      def install
        bin.install "hosts"
      end
    end
  end
end
