# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hosts < Formula
  desc "Manage host entries - a simple tool for a simple, but annoying task!"
  homepage "https://github.com/martinnirtl/hosts-cli"
  version "0.2.2"

  on_macos do
    url "https://github.com/martinnirtl/hosts-cli/releases/download/v0.2.2/hosts_Darwin_all.tar.gz"
    sha256 "5c81ad62b1520f4598bc2ea6a7e1ef1afe59d0c548746092b149102fd9c6e254"

    def install
      bin.install "hosts"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/martinnirtl/hosts-cli/releases/download/v0.2.2/hosts_Linux_x86_64.tar.gz"
      sha256 "f86be272297c6a7bc7b4e6dda10b455503376db2c43c960cdd94095a89b9fcaa"

      def install
        bin.install "hosts"
      end
    end
  end
end
